authapp/urls.py
from django.urls import path, re_path
from authapp import views, ajax_views

app_name = 'authapp'

urlpatterns = [
    # re_path(r'^email/key/send/$', views.email_key_send, name='email_key_send'),
    re_path(r'^email/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.primary_email_key_confirm, name='primary_email_key_confirm'),
    re_path(r'^password/reset/$', views.password_reset, name='password_reset'),
    re_path(r'^password/reset/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.password_reset_key_confirm, name='password_reset_key_confirm'),
    re_path(r'^password/change/$', views.password_change, name='password_change'),
    # re_path(r'^deactivate/$', views.deactivate_user, name='deactivate_user'),
    re_path(r'^delete/$', views.delete_user, name='delete_user'),
    re_path(r'^settings/$', views.settings, name='settings'),

    re_path(r'^logout/$', views.log_out, name='log_out'),

    re_path(r'^email_ask/$', views.email_ask, name='email_ask'),

    # ------------------------------------------------------------------------------
]

baseapp/urls.py
from django.urls import path, re_path
from authapp import views as authviews
from authapp import ajax_views as auth_ajax_views
from baseapp import ajax_views as base_ajax_views
from baseapp import views
from django.views.generic import TemplateView
from baseapp.sitemaps import sitemaps
from django.contrib.sitemaps import views as sitemap_views

app_name = 'baseapp'

urlpatterns = [
    re_path(r'^robots\.txt$',
            TemplateView.as_view(template_name="others/robots.txt", content_type="text/plain"), name="robots"),
    path('a/sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'baseapp:sitemaps'}),
    path('a/sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
            name='sitemaps'),


    re_path(r'^user/accounts/$', authviews.main_create_log_in, name='main_create_log_in'),

    re_path(r'^$', views.home, name='home'),
    re_path(r'^solo/$', views.solo_home, name="solo_home"),
    re_path(r'^group/$', views.group_home, name="group_home"),
    re_path(r'^all/$', views.all_home, name="all_home"),

    re_path(r'^pay/charge/$', views.pay_charge, name='pay_charge'),
    re_path(r'^pay/return/$', views.pay_return, name="pay_return"),
    re_path(r'^pay/cancel/return/$', views.pay_cancel_return, name="pay_cancel_return"),
    re_path(r'^pay/start/$', views.pay_start, name="pay_start"),

    re_path(r'^create/new/$', views.create_new, name="create_new"),
    re_path(r'^create/group/post/(?P<uuid>([0-9a-f]{32}))/$', views.create_group_post, name="create_group_post"),
    re_path(r'^create/solo/post/(?P<uuid>([0-9a-f]{32}))/$', views.create_solo_post, name="create_solo_post"),

    re_path(r'^update/group/post/(?P<uuid>([0-9a-f]{32}))/$', views.update_group_post, name="update_group_post"),
    re_path(r'^update/solo/post/(?P<uuid>([0-9a-f]{32}))/$', views.update_solo_post, name="update_solo_post"),

    re_path(r'^(?P<user_username>([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?))/$',
            views.user_profile, name='user_profile'),
    re_path(r'^solo/profile/(?P<uuid>([0-9a-f]{32}))/$', views.solo_profile, name="solo_profile"),
    re_path(r'^group/profile/(?P<uuid>([0-9a-f]{32}))/$', views.group_profile, name="group_profile"),

    re_path(r'^post/(?P<uuid>([0-9a-f]{32}))/$', views.post, name='post'),

    re_path(r'^solo/(?P<uuid>([0-9a-f]{32}))/$', views.solo_posts, name="solo_posts"),
    re_path(r'^group/(?P<uuid>([0-9a-f]{32}))/$', views.group_posts, name="group_posts"),

    re_path(r'^search/all/$', views.search_all, name='search_all'),
    re_path(r'^search/user/$', views.search_user, name='search_user'),
    re_path(r'^search/solo/$', views.search_solo, name='search_solo'),
    re_path(r'^search/group/$', views.search_group, name='search_group'),
    re_path(r'^search/post/$', views.search_post, name='search_post'),

    re_path(r'^note/all/$', views.note_all, name='note_all'),
    re_path(r'^follow/feed/$', views.follow_feed, name='follow_feed'),

    re_path(r'^log/charge/$', views.log_charge, name='log_charge'),
    re_path(r'^log/pay/$', views.log_pay, name='log_pay'),

    # --------------------------------------------------------------------------------
    re_path(r'^re_settings/ajax/$', auth_ajax_views.re_settings, name='re_settings'),
    re_path(r'^re_settings/ajax/upload_user_photo/$', auth_ajax_views.upload_user_photo, name='re_upload_user_photo'),
    # --------------------------------------------------------------------------------
    re_path(r'^re/create/search/$', base_ajax_views.re_create_search,
            name='re_create_search'),

    re_path(r'^re/create/check/server/time/$', base_ajax_views.re_create_check_server_time,
            name='re_create_check_server_time'),


    re_path(r'^re/create/group/post/$', base_ajax_views.re_create_group_post,
            name='re_create_group_post'),
    re_path(r'^re/create/group/post/complete/$', base_ajax_views.re_create_group_post_complete,
            name='re_create_group_post_complete'),


    re_path(r'^re/create/solo/post/$', base_ajax_views.re_create_solo_post,
            name='re_create_solo_post'),
    re_path(r'^re/create/solo/post/complete/$', base_ajax_views.re_create_solo_post_complete,
            name='re_create_solo_post_complete'),

    re_path(r'^re/update/group/post/$', base_ajax_views.re_update_group_post,
            name='re_create_group_post'),
    re_path(r'^re/update/group/post/complete/$', base_ajax_views.re_update_group_post_complete,
            name='re_create_group_post_complete'),

    re_path(r'^re/update/solo/post/$', base_ajax_views.re_update_solo_post,
            name='re_create_solo_post'),
    re_path(r'^re/update/solo/post/complete/$', base_ajax_views.re_update_solo_post_complete,
            name='re_create_solo_post_complete'),

    re_path(r'^re/profile/post/$', base_ajax_views.re_profile_post,
            name='re_profile_post'),
    re_path(r'^re/post/populate/$', base_ajax_views.re_post_populate,
            name='re_post_populate'),

    re_path(r'^re/comment/add/$', base_ajax_views.re_comment_add,
            name='re_comment_add'),
    re_path(r'^re/comment/delete/$', base_ajax_views.re_comment_delete,
            name='re_comment_delete'),
    re_path(r'^re/comment/more/load/$', base_ajax_views.re_comment_more_load,
            name='re_comment_more_load'),

    re_path(r'^re/post/like/$', base_ajax_views.re_post_like,
            name='re_post_like'),
    re_path(r'^re/post/like/list/$', base_ajax_views.re_post_like_list,
            name='re_post_like_list'),
    re_path(r'^re/profile/post/delete/$', base_ajax_views.re_profile_post_delete,
            name='re_profile_post_delete'),


    re_path(r'^re/follow/add/$', base_ajax_views.re_follow_add,
            name='re_follow_add'),
    re_path(r'^re/following/list/$', base_ajax_views.re_following_list,
            name='re_following_list'),
    re_path(r'^re/follower/list/$', base_ajax_views.re_follower_list,
            name='re_follower_list'),
    re_path(r'^re/solo/follow/$', base_ajax_views.re_solo_follow,
            name='re_solo_follow'),

    re_path(r'^re/group/follow/$', base_ajax_views.re_group_follow,
            name='re_group_follow'),

    re_path(r'^re/search/all/$', base_ajax_views.re_search_all,
            name='re_search_all'),
    re_path(r'^re/search/user/$', base_ajax_views.re_search_user,
            name='re_search_user'),
    re_path(r'^re/search/post/$', base_ajax_views.re_search_post,
            name='re_search_post'),
    re_path(r'^re/search/solo/$', base_ajax_views.re_search_solo,
            name='re_search_solo'),
    re_path(r'^re/search/group/$', base_ajax_views.re_search_group,
            name='re_search_group'),

    re_path(r'^re/note/all/$', base_ajax_views.re_note_all,
            name='re_note_all'),

    re_path(r'^re/follow/feed/$', base_ajax_views.re_follow_feed,
            name='re_follow_feed'),

    re_path(r'^re/nav/badge/populate/$', base_ajax_views.re_nav_badge_populate,
            name='re_nav_badge_populate'),

    re_path(r'^re/log/charge/$', base_ajax_views.re_log_charge,
            name='re_log_charge'),

    re_path(r'^re/log/pay/$', base_ajax_views.re_log_pay,
            name='re_log_pay'),

    # --------------------------------------------------------------------------------

    re_path(r'^re/home/rank/$', base_ajax_views.re_home_rank,
            name='re_home_rank'),
    re_path(r'^re/solo/rank/$', base_ajax_views.re_solo_rank,
            name='re_solo_rank'),
    re_path(r'^re/group/rank/$', base_ajax_views.re_group_rank,
            name='re_group_rank'),
    re_path(r'^re/all/rank/$', base_ajax_views.re_all_rank,
            name='re_all_rank'),

    re_path(r'^re/solo/posts/$', base_ajax_views.re_solo_posts,
            name='re_solo_posts'),
    re_path(r'^re/group/posts/$', base_ajax_views.re_group_posts,
            name='re_group_posts'),
]


from django.conf import settings

if settings.DEBUG:
    urlpatterns += [

        re_path(r'^b/admin/$', views.b_admin, name='b_admin'),
        re_path(r'^b/admin/solo/$', views.b_admin_solo, name='b_admin_solo'),
        re_path(r'^b/admin/group/$', views.b_admin_group, name='b_admin_group'),
        re_path(r'^b/admin/member/$', views.b_admin_member, name='b_admin_member'),
        re_path(r'^b/admin/group/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_group_edit, name='b_admin_group_edit'),
        re_path(r'^b/admin/solo/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_solo_edit, name='b_admin_solo_edit'),
        # --------------------------------------------------------------------------------

        re_path(r'^re/group/register/$', base_ajax_views.re_group_register,
                name='re_group_register'),
        re_path(r'^re/group/list/$', base_ajax_views.re_group_list,
                name='re_group_list'),
        re_path(r'^re/solo/register/$', base_ajax_views.re_solo_register,
                name='re_group_register'),
        re_path(r'^re/solo/list/$', base_ajax_views.re_solo_list,
                name='re_group_list'),

        re_path(r'^re/member/register/$', base_ajax_views.re_member_register,
                name='re_member_register'),

        re_path(r'^re/b/admin/group/delete/$', base_ajax_views.re_b_admin_group_delete,
                name='re_admin_group_delete'),
        re_path(r'^re/b/admin/group/edit/$', base_ajax_views.re_b_admin_group_edit,
                name='re_b_admin_group_edit'),
        re_path(r'^re/b/admin/group/edit/main/name/$', base_ajax_views.re_b_admin_group_edit_main_name,
                name='re_b_admin_group_edit_main_name'),
        re_path(r'^re/b/admin/group/upload/photo/$', base_ajax_views.re_b_admin_group_upload_photo,
                name='re_b_admin_group_upload_photo'),
        re_path(r'^re/b/admin/group/edit/main/photo/register/$',
                base_ajax_views.re_b_admin_group_edit_main_photo_register,
                name='re_b_admin_group_edit_main_photo_register'),

galabill/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path(r'^accounts/', include('authapp.urls')),
    re_path(r'^', include('baseapp.urls')),
    re_path(r'^payment/paypal', include('paypal.standard.ipn.urls')),
    # https://www.뭐뭐닷컴.com/payment/paypal 이걸 paypal의 ipn 설정에 입력하면 된다.
]

from django.views.generic import TemplateView
# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

authapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from authapp.models import UserUsername, UserPrimaryEmail

from PIL import Image
from django.core.files import File
from .models import UserPhoto, STATUS_CHOICES


class UserCreateForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'name'}))
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'username(id)'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                         'placeholder': 'password_confirm'}))

    year = forms.IntegerField(initial='', widget=forms.Select(attrs={'class': 'form-control', 'id': 'years', 'placeholder': 'Year'}), required=True)
    month = forms.IntegerField(initial='', widget=forms.Select(attrs={'class': 'form-control', 'id': 'months', 'placeholder': 'Month'}), required=True)
    day = forms.IntegerField(initial='', widget=forms.Select(attrs={'class': 'form-control', 'id': 'days', 'placeholder': 'Day'}), required=True)
    gender = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect(), required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'year', 'month', 'day', 'gender']


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control login-form',
                                                             'placeholder': 'username(id) or email',
                                                             'id': 'id_username_login'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control login-form',
                                                                 'placeholder': 'password',
                                                                 'id': 'id_password_login'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class EmailAddForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'enter email to add'}))

    class Meta:
        model = User
        fields = ['email']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'new Password'}))
    new_password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'new Password confirm'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordResetForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username(ID) or Email'}))

    class Meta:
        model = User
        fields = ['username']


class PasswordResetConfirmForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'new Password'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'new Password confirm'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordCheckBeforeDeactivationForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordCheckBeforeDeleteForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['password']

class PasswordChangeWithUserPKForm(forms.Form):
    pk = forms.IntegerField(widget=forms.HiddenInput(
        attrs={'class': 'form-control', 'placeholder': 'username(id)'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'new Password'}))
    new_password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'new Password confirm'}))

    class Meta:
        model = User
        fields = ['pk', 'password']


class UserPhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = UserPhoto
        fields = ('file_300', 'file_50', 'x', 'y', 'width', 'height', 'rotate',)

authapp/templates/authapp/_account_activation_email.html
{% autoescape off %}
Hi and Welcome {{ name }}, {{ username }}! From {{ site_name }}

This mail is to {{ email }}

Please enter the link below. To confirm your registration:

https://{{ domain }}{% url 'authapp:primary_email_key_confirm' uid=uid  token=token %}

{% endautoescape %}

authapp/templates/authapp/_header_title.html
<title>galabill</title>

authapp/templates/authapp/_password_reset_email.html
{% autoescape off %}
Hi {{ name }}, {{ username }}! From {{ site_name }}

This mail is to {{ email }}

Please enter the link below. To reset your password:

https://{{ domain }}{% url 'authapp:password_reset_key_confirm' uid=uid  token=token %}

{% endautoescape %}

authapp/templates/authapp/delete_user_done.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    {% include 'authapp/_header_title.html' %}

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% include 'others/header_static.html' %}
    {% load static from staticfiles %}
    <script src="{% static 'js/navbar.min.js' %}"></script>
    <script defer src="{% static 'js/validation_create.min.js' %}"></script>
</head>


<body class="light_background_color height_100">

{% include 'baseapp/_navbar.html' %}


<div class="container-fluid margin_top_50" style="">


    <div class="row">
        <div class="desktop_display_none">
            <div class="padding_10"></div>
            <div class="padding_10"></div>
            <div class="padding_10"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">

            <div class="col-sm-12">
                <div class="mobile_display_none padding_35"></div>
                <div class="mobile_display_none padding_35"></div>
                <p class="h3">Account has been deleted. It takes maybe about 2 weeks. If you login before that 2 weeks are not gone, 'Delete' will be canceled and you can use the account again.</p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="padding_10"></div>
        <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 clickable">
            <div class="row">
                <a href="{% url 'baseapp:main_create_log_in' %}">
                    <p class="h2 background_light" align="center">Return to main</p>
                </a>
            </div>
        </div>
    </div>
</div>

</body>
</html>

authapp/templates/authapp/password_reset_completed.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    {% include 'authapp/_header_title.html' %}

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% include 'others/header_static.html' %}
    {% load static from staticfiles %}

    <script defer src="{% static 'js/validation_create.min.js' %}"></script>


</head>
<body>
{% include 'others/bootstrap_tester.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            {% include 'authapp/_logo.html' %}
        </div>
    </div>
    <div class="row">
        <div class="padding_10"></div>
        <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 clickable">
            <div class="row">
                <a href="{% url 'baseapp:main_create_log_in' %}">
                    <div class="h2 clickable background_light" align="center">Return to main</div>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="desktop_display_none">
            <div class="padding_10"></div>
            <div class="padding_10"></div>
            <div class="padding_10"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">

            <div class="col-sm-12">
                <div class="mobile_display_none padding_35"></div>
                <div class="mobile_display_none padding_35"></div>
                <p class="h3">Password reset completed.</p>
            </div>
        </div>
    </div>
</div>
</body>
</html>

authapp/templates/authapp/settings.html
<!DOCTYPE html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    {% include 'authapp/_header_title.html' %}
    {% include 'others/header_static.html' %}
    {% load static from staticfiles %}
    {% include 'others/header_navbar.html' %}
    <script src="{% static 'js/settings.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'cropper/cropper.min.css' %}">
    <script src="{% static 'cropper/cropper.min.js' %}"></script>

</head>
<body class="light_background_color height_100">
{% include 'baseapp/_navbar.html' %}

<div class="container-fluid margin_top_50">
    <div class="row" style="">
        <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
            <div class="row">
                <div class="div_base" style="">
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4" style="" align="center"><span
                                    class="padding_5"
                                    style="">Account settings</span></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="row" align="center">
                                <img class="img_300_300" id="img_300" src="{{ user.userphoto.file_300_url }}">
                            </div>

                            <div class="row" align="center">
                                <p class="h4"><a href="#"><span class="clickable padding_5 chatkaboo_background_color" id="span_change_photo">Change</span></a> <a href="#"><span class="clickable padding_5 chatkaboo_background_color" id="span_base_reset">BaseReset</span></a></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4">Name change</p>
                            <p class="h5" id="p_name_desc">You can change your name.</p>
                            <p class="h5"><b>Current: </b><span id="span_current_name" class="current_name">{{ request.user.usertextname.name }}</span></p>
                        </div>
                        <div class="col-xs-9 padding_top_5">
                            <div class="input-group-lg">
                                <input class="width_100_i" id="input_name" placeholder="name input" type="text">
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <p class="h4"><a href="#"><span id="span_name"
                                    class="clickable padding_5 pastel_bc3">change</span></a></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4">Username(ID) change</p>
                            <p class="h5">Username(ID) can be changed.</p>
                            <p class="h5"><b>Current: </b><span id="span_current_username" class="current_name">{{ request.user.userusername.username }}</span></p>
                            <p class="h5" id="p_username_desc">Username is unique</p>
                        </div>
                        <div class="col-xs-9 padding_top_5">
                            <div class="input-group-lg">
                                <input class="width_100_i" id="input_username" placeholder="username input" type="text">
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <p class="h4"><a href="#"><span id="span_username"
                                    class="clickable padding_5 pastel_bc2">change</span></a></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4">Email change</p>
                            <p class="h5">After you change your email, confirmation email have to be checked in 10min.</p>
                            <p class="h5"><b>Current: </b><span id="span_current_email" class="current_name">{{ request.user.userprimaryemail.email }}</span></p>
                            <p class="h5" id="p_email_desc">Unless you confirm your email in 10min, It won't be changed.</p>
                        </div>
                        <div class="col-xs-9 padding_top_5">
                            <div class="input-group-lg">
                                <input class="width_100_i" id="input_email" placeholder="email input" type="text">
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <p class="h4"><a href="#"><span id="span_email"
                                    class="clickable padding_5 pastel_bc1">change</span></a></p>
                        </div>
                    </div>
                    {% if not user.userprimaryemail.is_permitted %}
                    <div class="row email_token_resend" id="email_token_send">
                        <div class="col-xs-12">
                            <p class="h4" id="p_resend_desc">Current you are not permitted. You should permit your email.</p>
                        </div>
                        <div class="col-xs-9 padding_top_5">
                            <p class="h4">Email Authentication Token Resend to ({{ user.userprimaryemail.email }})</p>
                        </div>
                        <div class="col-xs-3">
                            <p class="h4"><a href="#"><span
                                    class="clickable padding_5 pastel_bc1" id="span_resend">Resend</span></a></p>
                        </div>
                        <div class="col-xs-12">
                            <p class="h4 text-danger"></p>
                        </div>
                    </div>
                    {% endif %}
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4" style="" align="center"><a href="{% url 'authapp:password_change' %}"><span
                                    class="clickable pastel_bc1 padding_5">Password Change</span></a></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="h4" style="" align="center"><a href="{% url 'authapp:delete_user' %}"><span
                                    class="clickable pastel_bc3 padding_5">Delete account</span></a></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modal_crop" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body padding_0">
          <img src="" id="img_crop" class="max_width_100p">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Save</button>
        </div>
      </div>
    </div>
  </div>



<div class="modal fade" id="modal_base_reset">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Reset Profile image?</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" id="btn_base_reset_ok">OK</button>
        </div>
      </div>
    </div>
  </div>
<form class="hidden" method="post" enctype="multipart/form-data" id="form_upload">
    <input type="file" name="file" id="input_file" accept="image/jpeg, image/png" required >
</form>
</body>


</html>