authapp/urls.py
from django.urls import path, re_path
from authapp import views, ajax_views

app_name = 'authapp'

urlpatterns = [
    # re_path(r'^email/key/send/$', views.email_key_send, name='email_key_send'),
    re_path(r'^email/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.primary_email_key_confirm, name='primary_email_key_confirm'),
    re_path(r'^password/reset/$', views.password_reset, name='password_reset'),
    re_path(r'^password/reset/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.password_reset_key_confirm, name='password_reset_key_confirm'),
    re_path(r'^password/change/$', views.password_change, name='password_change'),
    # re_path(r'^deactivate/$', views.deactivate_user, name='deactivate_user'),
    re_path(r'^delete/$', views.delete_user, name='delete_user'),
    re_path(r'^settings/$', views.settings, name='settings'),

    re_path(r'^logout/$', views.log_out, name='log_out'),

    re_path(r'^email_ask/$', views.email_ask, name='email_ask'),

    # ------------------------------------------------------------------------------
]

baseapp/urls.py
from django.urls import path, re_path
from authapp import views as authviews
from authapp import ajax_views as auth_ajax_views
from baseapp import ajax_views as base_ajax_views
from baseapp import views
from django.views.generic import TemplateView
from baseapp.sitemaps import sitemaps
from django.contrib.sitemaps import views as sitemap_views

app_name = 'baseapp'

urlpatterns = [
    re_path(r'^robots\.txt$',
            TemplateView.as_view(template_name="others/robots.txt", content_type="text/plain"), name="robots"),
    path('a/sitemap.xml', sitemap_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'baseapp:sitemaps'}),
    path('a/sitemap-<section>.xml', sitemap_views.sitemap, {'sitemaps': sitemaps},
            name='sitemaps'),


    re_path(r'^user/accounts/$', authviews.main_create_log_in, name='main_create_log_in'),

    re_path(r'^$', views.home, name='home'),
    re_path(r'^solo/$', views.solo_home, name="solo_home"),
    re_path(r'^group/$', views.group_home, name="group_home"),
    re_path(r'^all/$', views.all_home, name="all_home"),

    re_path(r'^pay/charge/$', views.pay_charge, name='pay_charge'),
    re_path(r'^pay/return/$', views.pay_return, name="pay_return"),
    re_path(r'^pay/cancel/return/$', views.pay_cancel_return, name="pay_cancel_return"),
    re_path(r'^pay/start/$', views.pay_start, name="pay_start"),

    re_path(r'^create/new/$', views.create_new, name="create_new"),
    re_path(r'^create/group/post/(?P<uuid>([0-9a-f]{32}))/$', views.create_group_post, name="create_group_post"),
    re_path(r'^create/solo/post/(?P<uuid>([0-9a-f]{32}))/$', views.create_solo_post, name="create_solo_post"),

    re_path(r'^update/group/post/(?P<uuid>([0-9a-f]{32}))/$', views.update_group_post, name="update_group_post"),
    re_path(r'^update/solo/post/(?P<uuid>([0-9a-f]{32}))/$', views.update_solo_post, name="update_solo_post"),

    re_path(r'^(?P<user_username>([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?))/$',
            views.user_profile, name='user_profile'),
    re_path(r'^solo/profile/(?P<uuid>([0-9a-f]{32}))/$', views.solo_profile, name="solo_profile"),
    re_path(r'^group/profile/(?P<uuid>([0-9a-f]{32}))/$', views.group_profile, name="group_profile"),

    re_path(r'^post/(?P<uuid>([0-9a-f]{32}))/$', views.post, name='post'),

    re_path(r'^solo/(?P<uuid>([0-9a-f]{32}))/$', views.solo_posts, name="solo_posts"),
    re_path(r'^group/(?P<uuid>([0-9a-f]{32}))/$', views.group_posts, name="group_posts"),

    re_path(r'^search/all/$', views.search_all, name='search_all'),
    re_path(r'^search/user/$', views.search_user, name='search_user'),
    re_path(r'^search/solo/$', views.search_solo, name='search_solo'),
    re_path(r'^search/group/$', views.search_group, name='search_group'),
    re_path(r'^search/post/$', views.search_post, name='search_post'),

    re_path(r'^note/all/$', views.note_all, name='note_all'),
    re_path(r'^follow/feed/$', views.follow_feed, name='follow_feed'),

    re_path(r'^log/charge/$', views.log_charge, name='log_charge'),
    re_path(r'^log/pay/$', views.log_pay, name='log_pay'),

    # --------------------------------------------------------------------------------
    re_path(r'^re_settings/ajax/$', auth_ajax_views.re_settings, name='re_settings'),
    re_path(r'^re_settings/ajax/upload_user_photo/$', auth_ajax_views.upload_user_photo, name='re_upload_user_photo'),
    # --------------------------------------------------------------------------------
    re_path(r'^re/create/search/$', base_ajax_views.re_create_search,
            name='re_create_search'),

    re_path(r'^re/create/check/server/time/$', base_ajax_views.re_create_check_server_time,
            name='re_create_check_server_time'),


    re_path(r'^re/create/group/post/$', base_ajax_views.re_create_group_post,
            name='re_create_group_post'),
    re_path(r'^re/create/group/post/complete/$', base_ajax_views.re_create_group_post_complete,
            name='re_create_group_post_complete'),


    re_path(r'^re/create/solo/post/$', base_ajax_views.re_create_solo_post,
            name='re_create_solo_post'),
    re_path(r'^re/create/solo/post/complete/$', base_ajax_views.re_create_solo_post_complete,
            name='re_create_solo_post_complete'),

    re_path(r'^re/update/group/post/$', base_ajax_views.re_update_group_post,
            name='re_create_group_post'),
    re_path(r'^re/update/group/post/complete/$', base_ajax_views.re_update_group_post_complete,
            name='re_create_group_post_complete'),

    re_path(r'^re/update/solo/post/$', base_ajax_views.re_update_solo_post,
            name='re_create_solo_post'),
    re_path(r'^re/update/solo/post/complete/$', base_ajax_views.re_update_solo_post_complete,
            name='re_create_solo_post_complete'),

    re_path(r'^re/profile/post/$', base_ajax_views.re_profile_post,
            name='re_profile_post'),
    re_path(r'^re/post/populate/$', base_ajax_views.re_post_populate,
            name='re_post_populate'),

    re_path(r'^re/comment/add/$', base_ajax_views.re_comment_add,
            name='re_comment_add'),
    re_path(r'^re/comment/delete/$', base_ajax_views.re_comment_delete,
            name='re_comment_delete'),
    re_path(r'^re/comment/more/load/$', base_ajax_views.re_comment_more_load,
            name='re_comment_more_load'),

    re_path(r'^re/post/like/$', base_ajax_views.re_post_like,
            name='re_post_like'),
    re_path(r'^re/post/like/list/$', base_ajax_views.re_post_like_list,
            name='re_post_like_list'),
    re_path(r'^re/profile/post/delete/$', base_ajax_views.re_profile_post_delete,
            name='re_profile_post_delete'),


    re_path(r'^re/follow/add/$', base_ajax_views.re_follow_add,
            name='re_follow_add'),
    re_path(r'^re/following/list/$', base_ajax_views.re_following_list,
            name='re_following_list'),
    re_path(r'^re/follower/list/$', base_ajax_views.re_follower_list,
            name='re_follower_list'),
    re_path(r'^re/solo/follow/$', base_ajax_views.re_solo_follow,
            name='re_solo_follow'),

    re_path(r'^re/group/follow/$', base_ajax_views.re_group_follow,
            name='re_group_follow'),

    re_path(r'^re/search/all/$', base_ajax_views.re_search_all,
            name='re_search_all'),
    re_path(r'^re/search/user/$', base_ajax_views.re_search_user,
            name='re_search_user'),
    re_path(r'^re/search/post/$', base_ajax_views.re_search_post,
            name='re_search_post'),
    re_path(r'^re/search/solo/$', base_ajax_views.re_search_solo,
            name='re_search_solo'),
    re_path(r'^re/search/group/$', base_ajax_views.re_search_group,
            name='re_search_group'),

    re_path(r'^re/note/all/$', base_ajax_views.re_note_all,
            name='re_note_all'),

    re_path(r'^re/follow/feed/$', base_ajax_views.re_follow_feed,
            name='re_follow_feed'),

    re_path(r'^re/nav/badge/populate/$', base_ajax_views.re_nav_badge_populate,
            name='re_nav_badge_populate'),

    re_path(r'^re/log/charge/$', base_ajax_views.re_log_charge,
            name='re_log_charge'),

    re_path(r'^re/log/pay/$', base_ajax_views.re_log_pay,
            name='re_log_pay'),

    # --------------------------------------------------------------------------------

    re_path(r'^re/home/rank/$', base_ajax_views.re_home_rank,
            name='re_home_rank'),
    re_path(r'^re/solo/rank/$', base_ajax_views.re_solo_rank,
            name='re_solo_rank'),
    re_path(r'^re/group/rank/$', base_ajax_views.re_group_rank,
            name='re_group_rank'),
    re_path(r'^re/all/rank/$', base_ajax_views.re_all_rank,
            name='re_all_rank'),

    re_path(r'^re/solo/posts/$', base_ajax_views.re_solo_posts,
            name='re_solo_posts'),
    re_path(r'^re/group/posts/$', base_ajax_views.re_group_posts,
            name='re_group_posts'),
]


from django.conf import settings

if settings.DEBUG:
    urlpatterns += [

        re_path(r'^b/admin/$', views.b_admin, name='b_admin'),
        re_path(r'^b/admin/solo/$', views.b_admin_solo, name='b_admin_solo'),
        re_path(r'^b/admin/group/$', views.b_admin_group, name='b_admin_group'),
        re_path(r'^b/admin/member/$', views.b_admin_member, name='b_admin_member'),
        re_path(r'^b/admin/group/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_group_edit, name='b_admin_group_edit'),
        re_path(r'^b/admin/solo/edit/(?P<uuid>([0-9a-f]{32}))/$', views.b_admin_solo_edit, name='b_admin_solo_edit'),
        # --------------------------------------------------------------------------------

        re_path(r'^re/group/register/$', base_ajax_views.re_group_register,
                name='re_group_register'),
        re_path(r'^re/group/list/$', base_ajax_views.re_group_list,
                name='re_group_list'),
        re_path(r'^re/solo/register/$', base_ajax_views.re_solo_register,
                name='re_group_register'),
        re_path(r'^re/solo/list/$', base_ajax_views.re_solo_list,
                name='re_group_list'),

        re_path(r'^re/member/register/$', base_ajax_views.re_member_register,
                name='re_member_register'),

        re_path(r'^re/b/admin/group/delete/$', base_ajax_views.re_b_admin_group_delete,
                name='re_admin_group_delete'),
        re_path(r'^re/b/admin/group/edit/$', base_ajax_views.re_b_admin_group_edit,
                name='re_b_admin_group_edit'),
        re_path(r'^re/b/admin/group/edit/main/name/$', base_ajax_views.re_b_admin_group_edit_main_name,
                name='re_b_admin_group_edit_main_name'),
        re_path(r'^re/b/admin/group/upload/photo/$', base_ajax_views.re_b_admin_group_upload_photo,
                name='re_b_admin_group_upload_photo'),
        re_path(r'^re/b/admin/group/edit/main/photo/register/$',
                base_ajax_views.re_b_admin_group_edit_main_photo_register,
                name='re_b_admin_group_edit_main_photo_register'),

galabill/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path(r'^accounts/', include('authapp.urls')),
    re_path(r'^', include('baseapp.urls')),
    re_path(r'^payment/paypal', include('paypal.standard.ipn.urls')),
    # https://www.뭐뭐닷컴.com/payment/paypal 이걸 paypal의 ipn 설정에 입력하면 된다.
]

from django.views.generic import TemplateView
# 이 아래부분 미디어 파일 디벨롭모드에서 쓰기 위해 필요
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path('admin/', admin.site.urls),
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
        re_path(r'^a/admin/', admin.site.urls),
    ]

baseapp/models.py
from django.db import models

# Create your models here.

baseapp/forms.py
from django import forms
from object.models import GroupPhoto, SoloPhoto



# ---------------------------------------------------------------------------------

class BAdminGroupPhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = GroupPhoto
        fields = ('file_300', 'file_50', 'x', 'y', 'width', 'height', 'rotate',)


class BAdminSoloPhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = SoloPhoto
        fields = ('file_300', 'file_50', 'x', 'y', 'width', 'height', 'rotate',)

baseapp/templates/baseapp/_modal_populate.html
<div class="hidden" id="clicked_post_id"></div>

<div class="modal fade" id="modal_pop_menu">
    <div class="modal-dialog modal-dialog_menu">
      <div class="modal-content modal-content_menu">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body modal_pop_menu_body" id="modal_pop_menu_content">
            <div align="center">
                <input type="text" id="modal_pop_menu_input" class="modal_pop_menu_input">
            </div>
            <div align="center" class="modal_pop_menu_link_wrapper">
              <a href=""><span class="clickable modal_pop_menu_copy" id="modal_pop_menu_copy">copy link</span></a>
            </div>
            <div align="center" class="modal_pop_menu_link_wrapper">
              <a href=""><span class="clickable modal_pop_menu_locate" id="modal_pop_menu_locate">move to link</span></a>
            </div>
        </div>
      </div>
    </div>
</div>

<div class="hidden" id="post_liking_next_id"></div>
<div class="modal fade" id="modal_post_liking">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal_post_liking_wrapper">
            <div align="center">likes</div>
            <div id="modal_post_liking_list">

            </div>
            <a href=""><div class="hidden" align="center" id="modal_post_liking_more">more</div></a>
        </div>
      </div>
    </div>
</div>
<div class="modal fade" id="modal_need_login_pop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <div align="center">need to login</div>
            <a href="/user/accounts/"><div align="center" class="clickable modal_need_login_select">login / sign up</div></a>
        </div>
      </div>
    </div>
</div>

baseapp/templates/baseapp/_navbar.html
<nav class="navbar navbar-default navbar-fixed-top navbar_base">
    <div class="container-fluid padding_right_0">
        <ul class="nav navbar-nav navbar_ul_base">

            <li>
                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_home" href="{% url 'baseapp:home' %}">
                        <i id="i_home" class="glyphicon glyphicon-home"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_home" href="{% url 'baseapp:home' %}">
                        <i id="i_home" class="glyphicon glyphicon-home"></i>
                    </a>
                {% endif %}
            </li>
            <li>
                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_feed" href="{% url 'baseapp:follow_feed' %}">
                        <i id="i_feed" class="glyphicon glyphicon-list-alt"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_feed" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_feed" class="glyphicon glyphicon-list-alt"></i>
                    </a>
                {% endif %}
            </li>
            <li>

                {% if user.is_authenticated %}
                    <a class="padding_15_i" id="a_plus" href="{% url 'baseapp:create_new' %}">
                        <i id="i_plus" class="glyphicon glyphicon-plus"></i>
                    </a>
                {% else %}
                    <a class="padding_15_i" id="a_plus" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_plus" class="glyphicon glyphicon-plus"></i>
                    </a>
                {% endif %}

            </li>

            <li id="nav_div_ul_li_bsearch">
                {% if user.is_authenticated %}
                    {% if user.noticecount.count == 0 %}
                        <a class="padding_15_i" id="a_note" href="{% url 'baseapp:note_all' %}">
                            <i id="i_note" class="glyphicon glyphicon-certificate"></i>
                        </a>
                    {% else %}
                        <a class="padding_15_i" id="a_note" href="{% url 'baseapp:note_all' %}">
                            <span id="i_note" class="nav_note_count">{{ user.noticecount.count }}</span>
                        </a>
                    {% endif %}
                {% else %}
                    <a class="padding_15_i" id="a_note" href="{% url 'baseapp:main_create_log_in' %}">
                        <i id="i_note" class="glyphicon glyphicon-certificate"></i>
                    </a>
                {% endif %}

            </li>
            <li>
                <form class="navbar-form navbar-left mobile_display_none margin_top_bottom_10">
                    <div class="input-group input-group-sm">
                        <input class="form-control" placeholder="Search" id="search_desktop_input" type="text">
                        <div class="input-group-btn">
                            <i class="btn btn-default" id="search_desktop_btn"><i
                                    class="glyphicon glyphicon-search"></i>
                            </i>
                        </div>
                    </div>
                </form>
            </li>

            <li class="nav_li_last_option desktop_display_none">
                <a href="#" class="padding_15_i" id="nav_li_a_menu">
                    <i class="glyphicon glyphicon-menu-down"></i>
                </a>
            </li>

        </ul>
    </div>
</nav>

<span class="nav_badge" id="badge_home" data-u="#i_home"></span>
<span class="nav_badge" id="badge_feed" data-u="#i_feed"></span>
<span class="nav_badge" id="badge_plus" data-u="#i_plus"></span>
<span class="nav_badge" id="badge_note" data-u="#i_note"></span>

<div class="modal fade" id="modal_menu">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% if user.is_authenticated %}
                    <div class="row">
                        <p class="h4" align="center"><a href="/{{ user.userusername.username }}/"><span
                                class="clickable">My Page</span></a></p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'authapp:settings' %}"><span class="clickable">Settings</span></a>
                        </p>
                    </div>

                    <div class="row">
                        <p class="h4" align="center"><a href="https://twitter.com/mingu_gam" target="_blank"
                                                        rel="noopener noreferrer"><span
                                class="clickable">about/help</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="/mingu/"><span
                                class="clickable">about question</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'authapp:log_out' %}"><span class="clickable">Log out</span></a>
                        </p>
                    </div>
                {% else %}
                    <div class="row">
                        <p class="h4" align="center"><a href="{% url 'baseapp:main_create_log_in' %}"><span
                                class="clickable">Log in / Create new account</span></a></p>
                    </div>

                    <div class="row">
                        <p class="h4" align="center"><a href="https://twitter.com/mingu_gam" target="_blank"
                                                        rel="noopener noreferrer"><span
                                class="clickable">about/help</span></a>
                        </p>
                    </div>
                    <div class="row">
                        <p class="h4" align="center"><a href="/mingu/"><span
                                class="clickable">about question</span></a>
                        </p>
                    </div>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

baseapp/templates/baseapp/b_admin_solo.html
<!DOCTYPE html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>galabill solo list</title>
    {% include 'others/header_static.html' %}

    {% load static from staticfiles %}
    {% include 'others/header_navbar.html' %}


    <script src="{% static 'js/b_admin_solo.min.js' %}"></script>
</head>
<body class="light_background_color height_100">
<!--navbar start-->
{% include 'baseapp/_navbar.html' %}

<div class="hidden" id="page_kind">home</div>

<div class="hidden" id="last_pk"></div>

{% if user.is_authenticated %}
    <div class="hidden" id="user_id">{{ user.username }}</div>
{% else %}
    <div class="hidden" id="user_id"></div>
{% endif %}


<!--page info end -->

<div class="container-fluid margin_top_50">
    <div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
            <div class="row">
                <a href="{% url 'baseapp:b_admin' %}"><div class="h4">Main</div></a>
                <div><h3>Solo</h3></div>
                <div>name: <input id="name_input"></div>
                <div>desc: <input id="desc_input"></div>
                <a href=""><div style="background-color: silver" id="register">register</div></a>
                <div>delete id: <input id="id_delete_input"></div>
                <a href=""><div style="background-color: silver" id="id_delete">delete</div></a>

                <div id="obj_list">
                </div>
                <a href=""><div style="background-color: pink" id="more_load">more_load</div></a>

            </div>
        </div>
    </div>
</div>
</body>
</html>

baseapp/templates/baseapp/fail.html
{% include 'others/header_metas.html' %}

fail!!!

baseapp/templates/baseapp/pdt_cancel_return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cancel</title>
</head>
<body>
<h1>Pdt cancel payment</h1>
<br>
</body>
</html>

baseapp/templates/baseapp/success.html
success!!!

baseapp/templates/baseapp/user_profile.html
<!DOCTYPE html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>galabill {{ chosen_user.userusername.username }}</title>
    {% include 'others/header_static.html' %}

    <meta name="keywords" content="galabill, celebs, celebrity, rank, top100, {{ chosen_user.userusername.username }}"/>
    <meta name="author" content="galabill"/>
    <meta name="title" content="galabill"/>
    <meta name="description" content="make your bias up"/>

    <meta property="og:url" content="https://www.galabill.com{{ request.get_full_path }}"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="galabill"/>
    <meta property="og:site_name" content="galabill"/>
    <meta property="og:description" content="make your bias up"/>

    <meta property="og:image" content="{{ chosen_user.userphoto.file_300_url }}"/>

    <meta name="twitter:image" content="{{ chosen_user.userphoto.file_300_url }}">

    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@galabill"/>
    <meta name="twitter:creator" content="@{{ chosen_user.userusername.username }}">
    {% load static from staticfiles %}
    {% include 'others/header_navbar.html' %}
    <script src="{% static 'js/post_populate.min.js' %}"></script>
    <script src="{% static 'js/follower_following.min.js' %}"></script>
    <script src="{% static 'js/date_differ.min.js' %}"></script>

    <script src="{% static 'js/user_profile.min.js' %}"></script>

</head>
<body class="light_background_color height_100">
{% include 'baseapp/_navbar.html' %}
<div class="hidden" id="page_kind">user</div>

<div class="hidden" id="chosen_user_id">{{ chosen_user.username }}</div>
{% if user.is_authenticated %}
    <div class="hidden" id="user_id">{{ user.username }}</div>
{% else %}
    <div class="hidden" id="user_id"></div>
{% endif %}
<div class="hidden" id="last_post_id"></div>
<div class="hidden" id="delete_post_id"></div>

<!--page info end -->

<div class="container-fluid margin_top_50">
    <div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
            <div class="row" id="content">
                <div class="row div_base" id="chat_base">
                    <div align="center">
                        <img class="img_300_300" id="img_300"
                             src="{{ chosen_user.userphoto.file_300_url }}">
                    </div>

                    <div align="center" class="pro_user_text_name"><span>{{ chosen_user.usertextname.name }}</span>
                    </div>
                    <div align="center" class="pro_username"><span>{{ chosen_user.userusername.username }}</span></div>

                    <div class="row">
                        <div class="col-xs-6" align="right"><span class="pro_follow_explain">following: </span>
                            <a href="#">
                                <span id="count_following"
                                      class="pro_follow_count">{{ chosen_user.followingcount.count }}</span>
                            </a>
                        </div>
                        <div class="col-xs-6" align="left"><span class="pro_follow_explain">followers: </span>
                            <a href="#">
                                <span id="count_follower"
                                      class="pro_follow_count">{{ chosen_user.followercount.count }}</span>
                            </a>
                        </div>
                    </div>

                    {% if following == None %}
                        <div class="hidden" align="center" id="follow_wrapper">
                            <a href="">
                                <span class="clickable pro_follow" id="follow">follow</span>
                            </a>
                        </div>
                    {% else %}
                        <div class="hidden" align="center" id="follow_wrapper">
                            <a href="">
                                <span class="clickable pro_follow" id="follow">following <span
                                        class="glyphicon glyphicon-ok"></span></span>
                            </a>
                        </div>
                    {% endif %}
                    {% if chosen_user == user %}
                        <div align="right">
                            <span class="log_current">{{ user.wallet.gross }}</span>
                            <span class="log_current_dollar">$</span>
                        </div>
                        <div align="right">
                            <a href="{% url 'baseapp:log_charge' %}"><span
                                    class="log_pay_charge clickable">charge log</span></a>
                        </div>
                    {% endif %}

                </div>
                <div id="user_profile_post_list"></div>
                <a href="">
                    <div class="user_profile_more_load hidden" id="more_load" align="center">more load</div>
                </a>
            </div>
        </div>
    </div>
</div>

{% include 'baseapp/_modal_post_delete.html' %}
{% include 'baseapp/_modal_populate.html' %}
{% include 'baseapp/_modal_follow.html' %}

</body>
</html>